### ISSUE TITLE
Project name is invalid

### ISSUE THREAD

**Issue by playcat** [vanjadardic/KiTTY2#1]
... should be Kitty-ca 2, for historical reasons. And cultural, for that matter.

**Comment by vanjadardic** [comment]
Feel free to fork my project and change its name to whatever you want, since it's open-source.

**Comment by vanjadardic** [comment]
Since it's open-source

**Comment by playcat** [comment]
Fork yourself :)

**Comment by vanjadardic** [comment]
Yeah, I kinda knew using the term "fork" isn't the safest when answering your questions, but I just wanted to see if you would notice it...
